// Code generated by "stringer -type KeyKind -trimprefix KeyKind"; DO NOT EDIT.

package kvsqlite

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyKindUndefined-0]
	_ = x[KeyKindString-1]
	_ = x[KeyKindHash-2]
}

const _KeyKind_name = "UndefinedStringHash"

var _KeyKind_index = [...]uint8{0, 9, 15, 19}

func (i KeyKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KeyKind_index)-1 {
		return "KeyKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyKind_name[_KeyKind_index[idx]:_KeyKind_index[idx+1]]
}
