// Code generated by ./gen.py; DO NOT EDIT
package kvsqlite

import (
    "context"
    "database/sql"
)
            
type _StringHandleWithCtx struct{
    *_StringHandle
    ctx context.Context
}

func (tx TxWithCtx) String(key string) *_StringHandleWithCtx {
return &_StringHandleWithCtx{
    _StringHandle: tx.Tx.String(key),
    ctx: tx.ctx,
}
}
func (handle *_StringHandleWithCtx) Get () (Value, error) {
    return handle._StringHandle.Get(handle.ctx)  
}
func (handle *_StringHandleWithCtx) Set (val Value) error {
    return handle._StringHandle.Set(handle.ctx , val)  
}
func (handle *_StringHandleWithCtx) Incr (amount int64) (int64, error) {
    return handle._StringHandle.Incr(handle.ctx , amount)  
}
type _HashHandleWithCtx struct{
    *_HashHandle
    ctx context.Context
}

func (tx TxWithCtx) Hash(key string) *_HashHandleWithCtx {
return &_HashHandleWithCtx{
    _HashHandle: tx.Tx.Hash(key),
    ctx: tx.ctx,
}
}
func (handle *_HashHandleWithCtx) Get (filed string) (Value, error) {
    return handle._HashHandle.Get(handle.ctx , filed)  
}
func (handle *_HashHandleWithCtx) Incr (filed string, amount int64) (int64, error) {
    return handle._HashHandle.Incr(handle.ctx , filed, amount)  
}
func (handle *_HashHandleWithCtx) Exists (filed string) (bool, error) {
    return handle._HashHandle.Exists(handle.ctx , filed)  
}
func (handle *_HashHandleWithCtx) Size () (int, error) {
    return handle._HashHandle.Size(handle.ctx)  
}
func (handle *_HashHandleWithCtx) Items () (map[string]Value, error) {
    return handle._HashHandle.Items(handle.ctx)  
}
func (handle *_HashHandleWithCtx) Set (field string, val Value) error {
    return handle._HashHandle.Set(handle.ctx , field, val)  
}
func (handle *_HashHandleWithCtx) SetAll (vmap map[string]Value) error {
    return handle._HashHandle.SetAll(handle.ctx , vmap)  
}
func (handle *_HashHandleWithCtx) Clear () (int64, error) {
    return handle._HashHandle.Clear(handle.ctx)  
}
func (handle *_HashHandleWithCtx) Del (fields ...string) (int64, error) {
    return handle._HashHandle.Del(handle.ctx , fields...)  
}
func (handle *_HashHandleWithCtx) Keys () ([]string, error) {
    return handle._HashHandle.Keys(handle.ctx)  
}
type _ListHandleWithCtx struct{
    *_ListHandle
    ctx context.Context
}

func (tx TxWithCtx) List(key string) *_ListHandleWithCtx {
return &_ListHandleWithCtx{
    _ListHandle: tx.Tx.List(key),
    ctx: tx.ctx,
}
}
func (handle *_ListHandleWithCtx) Size () (int64, error) {
    return handle._ListHandle.Size(handle.ctx)  
}
func (handle *_ListHandleWithCtx) MaxIdx () (sql.Null[int64], error) {
    return handle._ListHandle.MaxIdx(handle.ctx)  
}
func (handle *_ListHandleWithCtx) MinIdx () (sql.Null[int64], error) {
    return handle._ListHandle.MinIdx(handle.ctx)  
}
func (handle *_ListHandleWithCtx) Nth (idx int) (Value, error) {
    return handle._ListHandle.Nth(handle.ctx , idx)  
}
func (handle *_ListHandleWithCtx) Push (val Value) error {
    return handle._ListHandle.Push(handle.ctx , val)  
}
func (handle *_ListHandleWithCtx) LPush (val Value) error {
    return handle._ListHandle.LPush(handle.ctx , val)  
}
func (handle *_ListHandleWithCtx) Page (cursor *int64, pagesize int64) ([]Value, int64, error) {
    return handle._ListHandle.Page(handle.ctx , cursor, pagesize)  
}
